/**
 * @fileoverview Authentication Context and Hooks
 * 
 * Manages JWT authentication state globally using React Context API.
 * Handles:
 * - User login/registration (currently mock implementation)
 * - JWT token generation and management
 * - Token persistence using localStorage
 * - Session restoration on app startup
 * - Automatic token expiration checking
 * 
 * @module context/AuthContext
 */

import React, { createContext, useState, useContext, ReactNode, useEffect } from 'react';

/**
 * Represents an authenticated user
 * @interface User
 * @property {string} id - Unique user identifier
 * @property {string} email - User email address
 * @property {'user' | 'admin'} role - User role (user or admin)
 */
export interface User {
  id: string;
  email: string;
  role: 'user' | 'admin';
}

export interface AuthContextType {
  user: User | null;
  token: string | null;
  isAuthenticated: boolean;
  loading: boolean;
  login: (email: string, password: string) => Promise<void>;
  logout: () => void;
  register: (email: string, password: string) => Promise<void>;
}

const AuthContext = createContext<AuthContextType | undefined>(undefined);

/**
 * AuthProvider Component
 * 
 * Provides authentication context to all child components.
 * 
 * Features:
 * - Initializes auth state from localStorage on mount
 * - Validates and restores JWT tokens automatically
 * - Provides login/logout/register functions to child components
 * - Handles token expiration checking
 * 
 * Usage:
 * ```jsx
 * <AuthProvider>
 *   <App />
 * </AuthProvider>
 * ```
 * 
 * @component
 * @param {Object} props - Component props
 * @param {ReactNode} props.children - Child components
 * @returns {React.ReactElement} Context provider wrapper
 */
export const AuthProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [user, setUser] = useState<User | null>(null);
  const [token, setToken] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  // Load token from localStorage on mount
  useEffect(() => {
    const savedToken = localStorage.getItem('authToken');
    if (savedToken) {
      // Verify token is still valid
      try {
        const decoded = decodeToken(savedToken);
        if (decoded && decoded.exp * 1000 > Date.now()) {
          setToken(savedToken);
          setUser(decoded.user);
        } else {
          localStorage.removeItem('authToken');
        }
      } catch (error) {
        localStorage.removeItem('authToken');
      }
    }
    setLoading(false);
  }, []);

  const login = async (email: string, _password: string): Promise<void> => {
    try {
      // In a real app, this would call your backend API
      // For demo purposes, we'll create a mock JWT token
      const mockToken = generateMockToken(email);
      const decoded = decodeToken(mockToken);

      if (decoded) {
        setToken(mockToken);
        setUser(decoded.user);
        localStorage.setItem('authToken', mockToken);
      }
    } catch (error) {
      throw new Error('Login failed');
    }
  };

  const register = async (email: string, _password: string): Promise<void> => {
    try {
      // In a real app, this would call your backend API
      // For demo purposes, we'll create a mock JWT token
      const mockToken = generateMockToken(email);
      const decoded = decodeToken(mockToken);

      if (decoded) {
        setToken(mockToken);
        setUser(decoded.user);
        localStorage.setItem('authToken', mockToken);
      }
    } catch (error) {
      throw new Error('Registration failed');
    }
  };

  const logout = (): void => {
    setUser(null);
    setToken(null);
    localStorage.removeItem('authToken');
  };

  return (
    <AuthContext.Provider
      value={{
        user,
        token,
        isAuthenticated: !!token && !!user,
        loading,
        login,
        logout,
        register,
      }}
    >
      {children}
    </AuthContext.Provider>
  );
};

/**
 * Hook to access authentication context
 * 
 * Must be used within an AuthProvider context.
 * Provides access to user state, token, and authentication functions.
 * 
 * Example:
 * ```typescript
 * const { user, isAuthenticated, login, logout } = useAuth();
 * ```
 * 
 * @hook
 * @returns {AuthContextType} Authentication context value
 * @throws {Error} If used outside of AuthProvider
 */
export const useAuth = (): AuthContextType => {
  const context = useContext(AuthContext);
  if (!context) {
    throw new Error('useAuth must be used within an AuthProvider');
  }
  return context;
};

/**
 * Generates a mock JWT token for demo purposes
 * 
 * ⚠️ WARNING: This is for DEMO ONLY
 * In production, tokens should be generated by a secure backend server.
 * 
 * Token structure:
 * - Header: { alg: 'HS256', typ: 'JWT' }
 * - Payload: { user: {...}, iat, exp }
 * - Signature: mock (not verified)
 * 
 * Token expiration: 24 hours from generation
 * 
 * @function
 * @param {string} email - User email address
 * @returns {string} Base64-encoded JWT token (Header.Payload.Signature)
 */
function generateMockToken(email: string): string {
  const header = {
    alg: 'HS256',
    typ: 'JWT',
  };

  const payload = {
    user: {
      id: `user_${Date.now()}`,
      email: email,
      role: email.includes('admin') ? 'admin' : 'user',
    },
    iat: Math.floor(Date.now() / 1000),
    exp: Math.floor(Date.now() / 1000) + 24 * 60 * 60, // 24 hour expiry
  };

  const encodedHeader = btoa(JSON.stringify(header));
  const encodedPayload = btoa(JSON.stringify(payload));
  const signature = btoa('mock-signature');

  return `${encodedHeader}.${encodedPayload}.${signature}`;
}

/**
 * Decodes a JWT token to extract payload information
 * 
 * Extracts and parses the payload section of a JWT token.
 * Does NOT verify the signature (use server-side verification in production).
 * 
 * @function
 * @param {string} token - JWT token to decode (Header.Payload.Signature format)
 * @returns {any} Decoded payload object or null if invalid token format
 */
export function decodeToken(token: string): any {
  try {
    const parts = token.split('.');
    if (parts.length !== 3) {
      return null;
    }

    const decoded = JSON.parse(atob(parts[1]));
    return decoded;
  } catch (error) {
    return null;
  }
}
